# Generated by Django 6.0.2 on 2026-02-24 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('period', models.CharField(max_length=100)),
                ('dynasty', models.CharField(max_length=100)),
                ('visiting_hours', models.CharField(max_length=200)),
                ('entry_fee', models.CharField(blank=True, max_length=200)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='monuments/main/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='monuments/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('monument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.monument')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tour_type', models.CharField(choices=[('360', '360° Interactive Tour'), ('video', 'Video Tour'), ('audio', 'Audio Guide')], max_length=20)),
                ('panorama_image', models.ImageField(blank=True, null=True, upload_to='tours/360/')),
                ('video_url', models.URLField(blank=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='tours/videos/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='tours/audio/')),
                ('description', models.TextField()),
                ('duration_minutes', models.IntegerField(default=30)),
                ('is_published', models.BooleanField(default=True)),
                ('monument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tours.monument')),
            ],
        ),
    ]
