# Generated by Django 6.0.2 on 2026-02-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monumentimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='monuments/gallery/'),
        ),
    ]
