# Generated by Django 6.0.2 on 2026-05-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_monumentimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monument',
            name='entry_fee',
            field=models.CharField(blank=True, default='Free', max_length=200),
        ),
        migrations.AlterField(
            model_name='monument',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='monument',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='monument',
            name='visiting_hours',
            field=models.CharField(default='10:00 AM - 6:00 PM', max_length=200),
        ),
    ]
