# Generated by Django 6.0.2 on 2026-05-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='content/'),
        ),
    ]
